### ISSUE TITLE
import no longer works after upgrading to v0.0.3

### ISSUE THREAD

**Issue by dschinkel** [matthewhudson/current-device#113]
My import was working fine before I upgraded

`import { device } from 'device.js';`

how do I need to change this to work now with `v0.0.3`?

Side question: why do I no longer see a `lib` folder if I look at `devicejs` in node_modules?

**Comment by maxneuvians** [comment]
Looks like it got added to `.gitignore`, not sure why. This works for me in my `package.json`:

```
"device.js": "git+https://github.com/matthewhudson/device.js.git#6cbf759608029f524edefc2b67ef5b8e8a9ee385",
```

**Comment by JSteunou** [comment]
wrong repo I guess, there is no v0.0.3 of this lib

**Comment by matthewhudson** [comment]
@dschinkel @maxneuvians I'm closing, please reopen and provide more details if the [installation guide](https://github.com/matthewhudson/current-device#installation) doesn't work out for you.
