### ISSUE TITLE
TypeError: device is undefined

### ISSUE THREAD

**Issue by kiran-gupta** [matthewhudson/current-device#163]
https://thematthewhudson.com/current-device/
Demo is also not working.  There is a error in console "TypeError: device is undefined" after you had made the changes.

**Comment by matthewhudson** [comment]
@kiran-gupta Great catch. Looks like the module definition is slightly different:

Recent stable release: [v0.7.2](https://unpkg.com/current-device@0.7.2/umd/current-device.js)
Current release: [v0.7.7](https://unpkg.com/current-device@0.7.7/umd/current-device.js)

**Comment by Er-rchydy** [comment]
@matthewhudson  hi is there a way to use the current release ? 
the device `variable` is still undefined.  `Uncaught TypeError: Cannot read property 'os' of undefined`
thanks

**Comment by matthewhudson** [comment]
It's a demo/docs error, I've resolved in [0.8.0](https://unpkg.com/current-device@0.8.0/umd/current-device.min.js).
