### ISSUE TITLE
Incorrect orientation detection on iOS for standalone app

### ISSUE THREAD

**Issue by ilarysid** [matthewhudson/current-device#180]
When you add a webpage to the Home Screen and then run the web page as a standalone app the is  orientation detected incorrectly: when you change the device orientation, the portrait mode is recognized as landscape and the landscape mode is recognized as portrait.

**Comment by khum08** [comment]
Did you find some solution? I met the same problem.

**Comment by khum08** [comment]
> When you add a webpage to the Home Screen and then run the web page as a standalone app the is orientation detected incorrectly: when you change the device orientation, the portrait mode is recognized as landscape and the landscape mode is recognized as portrait.

Did you find some solution? I met the same problem.
