### ISSUE TITLE
Orientation change does not work properly on iPhone X Safari

### ISSUE THREAD

**Issue by uxblonde** [matthewhudson/current-device#191]
1. Open [demo] on iPhone X Safari:

![1-after-pageload](https://user-images.githubusercontent.com/35133783/52130034-c87ee580-2641-11e9-9e61-36ee451ffef2.jpeg)

2. After first orientation change `.portrait` still remains.

![2-after-portrait-to-landscape](https://user-images.githubusercontent.com/35133783/52130035-c9177c00-2641-11e9-8c08-6ecd2e0d164e.jpeg)

3. After second orientation change class switches to `.landscape`, but orientation is portrait.

![3-after-landscape-to-portrait](https://user-images.githubusercontent.com/35133783/52130036-c9177c00-2641-11e9-9a89-5abfa93191fb.jpeg)

[demo]:http://thematthewhudson.com/current-device/

**Comment by SilencerWeb** [comment]
Facing the same issue in Chrome on iPad

**Comment by harwee** [comment]
@uxblonde @SilencerWeb  were you able to solve this problem?

**Comment by thomasjonas** [comment]
Same problem on iPhone7 + Safari

**Comment by uxblonde** [comment]
> @uxblonde @SilencerWeb were you able to solve this problem?

No

**Comment by matthewhudson** [comment]
@uxblonde @SilencerWeb -

I approved and released a fix courtesy of @thomasjonas - can you test w/ v0.9.1?

**Comment by uxblonde** [comment]
That's weird, but I'm not seeing a problem with the old version on iPhoneX right now (I think it's version 0.8.0, I can't say for sure).
The demo page with version 0.9.0(?) also works correctly.

**Comment by thomasjonas** [comment]
I noticed the demo page is actually 0.9.1 but has 0.9.0 in the comments. The url is includes 0.9.1 and I also checked if my code is in there, which it is. @matthewhudson did you maybe forget to change the version number in the comment?

I've just tested the demo page on BrowserStack again on iOS versions 10, 11, 12 and 13 beta and it all seems to work as expected.
