### ISSUE TITLE
walkOnChangeOrientationList : for...in on changeOrientationList enumerates inherited properties.

### ISSUE THREAD

**Issue by pieshop** [matthewhudson/current-device#216]
I've just dealt with an issue in IE11. The specific issue is caused by:

```
function walkOnChangeOrientationList(newOrientation) {
  for (const index in changeOrientationList) {
    changeOrientationList[index](newOrientation)
  }
}
```
When using for...in on an array it enumerates inherited properties. In my project this only proved an issue in IE11. It was iterating an empty array and enumerating 'find' resulting in:

```
[]['find'](newOrientation)
```

This was causing a third party library to blow up!

**Comment by matthewhudson** [comment]
Thanks for flagging @pieshop and describing the issue. Mind opening a PR?
