### ISSUE TITLE
Type definition file not included in package

### ISSUE THREAD

**Issue by rann91** [matthewhudson/current-device#235]
I'm using this package with TypeScript. When I install the package, the  **index.d.ts** is not included in the bundle. See https://snipboard.io/OUVaKF.jpg. I think it's because the types reference in package.json is set to "lib/types/index.d.ts", while the lib/ folder is being ignored.

I'm using the latest version: 0.10.0

**Comment by bparish628** [comment]
@matthewhudson Anyway we could get a release that includes these types? Looks like it was merged in September, but it's not in any releases yet.

**Comment by matthewhudson** [comment]
@bparish628 Thank you for reporting! I just published the fix in #@v0.10.2.
