### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by matthewhudson** [matthewhudson/current-device#85]
@megawac Thanks for [reminding me](https://github.com/matthewhudson/device.js/issues/71#issuecomment-65281186) of this!

**Comment by fourcube** [comment]
+1 and thank for your work!

**Comment by o1y** [comment]
please push :)

**Comment by roughcoder** [comment]
+1 before ports get added.

**Comment by tborychowski** [comment]
:+1:

**Comment by marnusw** [comment]
Yes please. And can it be made more Common.js friendly?

**Comment by JSteunou** [comment]
+1 @matthewhudson  switching to full npm, like a lot of people I think, this became urgent.

It's as easy as running "npm publish"

**Comment by matthewhudson** [comment]
@JSteunou @marnusw @tborychowski @roughcoder @o1y @fourcube  I'm working with @soenkekluth to make this possible - who has graciously offered the NPM "device.js" name. Anyone have a problem with the name - any desire for something else?

**Comment by marnusw** [comment]
Great news @matthewhudson, I think `device.js` is spot on.

**Comment by fourcube** [comment]
@matthewhudson thank you for finding the time to do this. :+1: for `device.js`.

**Comment by JSteunou** [comment]
@matthewhudson :+1:

**Comment by track0x1** [comment]
When is this coming to npm??

**Comment by JimmyMultani** [comment]
+1

Any news on this @matthewhudson? :)

**Comment by auschmann** [comment]
Would be nice to see this on NPM.

**Comment by enrtama** [comment]
+1

@matthewhudson how's this issue going?

**Comment by dryoma** [comment]
Bump. Will you be releasing this?

**Comment by JSteunou** [comment]
Seems like https://github.com/soenkekluth/device.js has taking the project ;)

**Comment by matthewhudson** [comment]
Yep, unfortunately. 

I suppose I could rename the lib to `sniffjs` - which is available in the registry.

Before I do so, does anybody have a better approach (or at least a better name) in mind?

**Comment by JSteunou** [comment]
Ho so I guess you did not volontary give up the device.js name ?

**Comment by matthewhudson** [comment]
Looks like the best solution is just renaming the project. Here's my thinking:
https://github.com/matthewhudson/device.js/pull/109

CC @megawac @fourcube @o1y @roughcoder @tborychowski @marnusw @JSteunou @track0x1 @JimmyMultani @auschmann @enrtama @dryoma

**Comment by matthewhudson** [comment]
MIssion accomplished: https://www.npmjs.com/package/current-device

**Comment by JSteunou** [comment]
@matthewhudson dont forget to git tag, so release page list all the tags and users can check what's the last / old releases.

**Comment by matthewhudson** [comment]
@JSteunou Good call, punted on that momentarily. I want to refine the release process and add a changelog. Open to tooling / thoughts there.

**Comment by JSteunou** [comment]
I'm using `npm version` to let it tag & update package.json version then npm script preversion to trigger tests & lint and postversion to pull push merge etc.
