### ISSUE TITLE
Iphone 6 Plus Site breaks.

### ISSUE THREAD

**Issue by goranefbl** [matthewhudson/current-device#92]
Great script,

I am using it in my site, wordpress theme, and everything works fine except iphone 6 plus landscape where site just breaks. If i use minified version then its not working on both portrait and landscape.

You can see it here: http://wp.logicathemes.com/iva/

When i turn off the script, site loads just fine.

Is there an easy way to debug it ?

Thanks for help.

**Comment by matthewhudson** [comment]
@goranefbl I'm unable to reproduce this error on http://matthewhudson.me/projects/device.js/

Can you please visit that page on an iPhone 6 Plus and confirm the error exists?

I suspect you may have a conflict somewhere else in your code.

**Comment by coliff** [comment]
Hey @goranefbl - you definitely need to optimise your site for delivering to mobile.
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwp.logicathemes.com%2Fiva%2F&tab=mobile
